version: 2

sources:
  - name: ecoride_bronze
    schema: bronze
    tables:
      - name: customers
      - name: sales
      - name: vehicles
      - name: product_reviews

  - name: chargenet_bronze
    schema: bronze
    tables:
      - name: charging_sessions
      - name: stations

  - name: vehicle_health_bronze
    schema: bronze
    tables:
      - name: logs
