gold:
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: password
      dbname: lakehouse
      schema: gold
      threads: 1
  target: dev