gold:
  outputs:
    dev:
      type: dremio
      threads: 1
      software_host: localhost
      port: 9047
      user: dremio
      password: dremio123
      use_ssl: false
      dremio_space: Nessie
      dremio_space_folder: gold
  target: dev